### ISSUE TITLE
run with ubuntu18.04

### ISSUE THREAD

**Issue by chengwei0427** [rvp-group/mad-icp#1]
Hi, dear author @digiamm @LeoBrizi @simone-ferrari 
      Thanks for your nice work. It looks amazing. 
      For some reason, I wanted to run this project in ubuntu18.04(gcc,g++ 9.4), but some Python-based dependencies failed to install, so I wrote a c++ data read section instead of the original python code. [code with c++ read](https://github.com/chengwei0427/mad-icp)
       But there is a program crash in operation, hope to get your help.
![2024-06-04 17-02-30屏幕截图](https://github.com/rvp-group/mad-icp/assets/20199999/2b03e166-42e3-4d0a-95fc-bf31a3613caa)
you can edit the params in [mad-icp/config/mapping_bag.yaml](https://github.com/chengwei0427/mad-icp/blob/c1a6d29a9df8b9339a4a7606809c77e1ca4513b2/mad-icp/config/mapping_bag.yaml#L5)

**Comment by digiamm** [comment]
Hi, @chengwei0427, thanks for your interest. We are in the middle of the release. We will soon (by the end of the week) release both C++ and Python executables to run our code; we are currently working on this. As for Python, we want to make our C++ executables rosless; you should be able to read rosbags but without having full ROS installed. In the near future, we will probably make some optional deps for ROS2.

**Comment by chengwei0427** [comment]
Hi, @digiamm 
Thans for your patient response.
Glad to hear that you will have a c++ version, looking forward to your new version release.

**Comment by digiamm** [comment]
Hi @chengwei0427, just pushed a C++ executable. Have a look at the end of the readme for building/using. The executable can be used only for bin format clouds and does not have a viewer. Now should be easier for you if you want to plug and work with ROS. Otherwise, you can convert bags in bin format with a converter like [kitti2rosbag](https://github.com/leofansq/Tools_RosBag2KITTI).

**Comment by chengwei0427** [comment]
Hi, @digiamm 
Thanks for your amazing work, I will test it and give you a feedback.Thanks again.

**Comment by chengwei0427** [comment]
Hi, @digiamm 
Thanks for your nice work, now I can run mad_icp with ROS. The ROS Version code is here [ros version](https://github.com/chengwei0427/mad-icp).
Here's a demo video
https://github.com/rvp-group/mad-icp/assets/20199999/38e7a1ee-3c49-479f-84f2-9f58aa3c72e0

**Comment by chengwei0427** [comment]
If you agree, maybe I can submit a PR.

**Comment by digiamm** [comment]
Hi @chengwei0427,

Thanks for your nice work. We are currently developing a `pip` package, which will be reflected in some refactoring in the code. Indeed, we appreciate your contribution. We want to have optional ROS/ROS2 dependencies, if you would like to make the ROS one (as you already did) that would be great. 

I will let you know once we finish with `pip` so you can you can open a pull request! Thanks again..
