### ISSUE TITLE
about deskew

### ISSUE THREAD

**Issue by chengwei0427** [rvp-group/mad-icp#2]
Hi, @digiamm 

I wonder why not use the time inside the laser for distortion correction [here](https://github.com/rvp-group/mad-icp/blob/a89a789b3332f6ad0176603e5862122f6c14592a/mad-icp/src/odometry/pipeline.cpp#L109)? Many types of lasers contain time information channels in the data output.
And in my tests, setting deskew to true causes some lo results to be worse.

**Comment by digiamm** [comment]
Hi, @chengwei0427. Thanks for pointing out this. You all right, our deskewing is based on constant motion assumption (as usually done in robotics) and azimutal-segmentation. This has been done to accomplish mechanical LiDARs independently from their model. Indeed, as you mentioned, this has limitations. We can talk about some way to put together this additional information. We are always happy to improve!

**Comment by chengwei0427** [comment]
Hi, @digiamm 
Thanks for your patient response.
In practice, we often come across different types of lidar, such as semi-solid lidar like livox or mechanical lidar like velodyne, which all provide timestamp information for each point, maybe we can use them.For example, when parsing data, synchronously parse time information, a simple example in my project like [this](https://github.com/chengwei0427/mad-icp/blob/4f255e043b59eb70bdd682270c1c2f925f1d81e5/mad-icp/src/preprocess/cloud_convert2/cloud_convert2.cc#L115)

**Comment by digiamm** [comment]
You all right, but sometimes you don't find this information (especially in older LiDARs), that's why we generalized to the simplest solution. However, in the near future, we plan to develop some bridges and small specializations for different sensors. With this current release, we mainly focused on existing SLAM benchmarks. We like your solution anyway!
