### ISSUE TITLE
Published supplemetary material

### ISSUE THREAD

**Issue by fdila** [rvp-group/mad-icp#6]
Hi, and thanks for your work!
I have a quick question on the supplementary material: I don't see it in the IEEE page (https://ieeexplore.ieee.org/document/10669999). 
I found the supplementary on arXiv, is it updated to the published version?

Thanks,

**Comment by digiamm** [comment]
Hi @fdila, you can take a look [here](https://github.com/rvp-group/mad-icp/blob/main/paper_with_supplementary.pdf), this is up to date!

**Comment by fdila** [comment]
Thanks!
