### ISSUE TITLE
Running with ROS2 bag

### ISSUE THREAD

**Issue by jacob-02** [rvp-group/mad-icp#7]
How exactly can I run my ros2 bag with this project?

**Comment by simone-ferrari** [comment]
To run our pipeline you can follow _exactly_ the instructions in the **README**, section **Usage**.
First, create a `ros2.cfg` file for your ros2 dataset. You can also copy one of the configurations in `configurations/datasets`, just be careful setting the right topic.

```bash
mad_icp --data-path /input_dir/ \
        --estimate-path /output_dir/ \
        --dataset-config /path_to_your_cfg/ros2.cfg
```

Notice that `input_dir` must contain either a `.mcap` bag or a `.db3` with its associated `.yaml` file.
