### ISSUE TITLE
Running mad_icp with a folder of pcds

### ISSUE THREAD

**Issue by Efesendil** [rvp-group/mad-icp#8]
Hello,

Are you planning to release a version of mad_icp that includes the <pcd_folder/> option as input, like for kiss_icp standalone?

Thank you.

**Comment by simone-ferrari** [comment]
Hi @Efesendil ! At the moment we do not have plans to release a PCD reader. However, if you manage to implement such compatibility, we welcome you to open a pull request. Alternatively, I suggest converting your PCD files into one of the supported formats.
