### ISSUE TITLE
Problem evaluating trajectories with EVO

### ISSUE THREAD

**Issue by yrq0208** [rvp-group/mad-icp#9]
Hi,

Thanks for open-sourcing this interesting work.

I have built MAD-ICP from source using cmake and make, and tried evaluating and reproducing the results using KITTI. So far I have tried KITTI 00 and 01 sequences but when I tried to evaluate the trajectory and calculate the ATE and RPE using EVO (https://github.com/MichaelGrupp/evo), I kept running into this error: "KITTI pose files must have 12 entries per row and no trailing delimiter at the end of the rows (space)". 

The output trajectory file of MAD-ICP indeed has 12 entries per row and no trailing delimiter of any sorts at the end of each row, there is probably spaces so I tried using this ubuntu command (sed 's/[[:blank:]]*$//' estimate.txt) to remove them. But this does not seem to work and I am still having the same error as mentioned before.

I wonder have you seen this error before and if you have, how do you solve it? If you are not using EVO, what software do you use to calculate the ATE and RPE of the trajectory?

Thank you in advance and I am looking forward to hearing from you.

**Comment by simone-ferrari** [comment]
Hi, I have just pushed some changes that should solve your problem, regardless of whether you run MAD in Python or C++. I tested EVO with these changes and it works as expected. However, as we clearly explain in our paper, for evaluating RPE we employ the KITTI [odometry development kit](https://www.cvlibs.net/datasets/kitti/eval_odometry.php).
